
name: .NET Build 

on:
  push        :
    branches: [ "master" ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

env: { DOTNET_NOLOGO: true, DOTNET_CLI_TELEMETRY_OPTOUT: true, DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true, }

jobs:
  test-maui-desktop-app-on-windows-platform:
    runs-on: windows-latest
    name   : Test MAUI Desktop App On Windows Platform
    steps:

      #--- Install Environment ---#
    
      - 
        name: Checkout
        uses: actions/checkout@v4.1.1
      -
        name: Setup .NET Core 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
          include-prerelease: true
      -
        name: Setup JDK 11
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '11'
          distribution: 'microsoft'
      -
        name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1
        with:
          vs-prerelease: true
      -
        name: Install MAUI Workloads
        run : | 
          dotnet workload install maui --ignore-failed-sources
      -
        name: Install Chocolatey (Windows Package Manager)
        uses: crazy-max/ghaction-chocolatey@v3.0.0
        with:
          args: -h  
      -
        name: Install Edge Webview2 Runtime
        run : |
          choco install webview2-runtime

      #--- Build ---#
          
      - 
        name: Restore dependencies
        run : |
          dotnet restore
      -
        name: Build
        working-directory: ./DAL
        run : |
          msbuild DAL.csproj -r -p:Configuration=Debug -p:RestorePackages=false

      #--- _Normal_ Testing ---#

      -
        name: Test
        run : |
          dotnet test --verbosity normal

      #--- Mutation Testing ---#

      -
        name: Mutation Test
        working-directory: ./UnitTesting
        run : |
          dotnet   tool restore
          dotnet dotnet-stryker
      -
        name: Upload Mutation Report
        uses: actions/upload-artifact@v3.1.3
        with:
          name: dotnet-stryker-mutation-report
          path: ./StrykerOutput/**/**/*.html
